### ISSUE TITLE
Plugin dont remove the selected pattern after use

### ISSUE THREAD

**Issue by LasseHaslev** [vitalk/vim-simple-todo#13]
After using the ,x mapping the text keeps selected.
I think it should be removing the selected pattern after use.

**Comment by vitalk** [comment]
This is expected behavior, after marking todo as done/undone I usually use
the <kbd>n</kbd>, <kbd>N</kbd> keys to jump between remaining items in this
category.

I prefer explicitly clear the last used search pattern (from my [.vimrc](https://github.com/vitalk/sanevi/blob/master/keybindings.vim#L86)):

```viml
nnore <esc><esc> :let @/ ""<cr>
```

Thank you for reporting, looks like I should add a note into documentation
about this behavior.
